### ISSUE TITLE
REST route alias (class cloaking)

### ISSUE THREAD

**Issue by Pavel910** [Webiny/Framework#22]
I have a custom map of my API services. I manually check if requested url matches one of them, and initialize Rest class manually:

``` yaml
RestServices:
    TemplateProvider: \Modules\Core\Common\Php\Services\TemplateProvider
    SiteWideConstants: \Modules\Core\Common\Php\Services\SiteWideConstants
```

``` php
$parts = $this->httpRequest()->getCurrentUrl(true)->getPath(true)->explode('/')->filter()->values()->val();
$serviceClass = $this->getConfig('RestServices.' . $parts[0]);

// Route using custom service map
$rest = new Rest($restApi, $serviceClass);
$response = $rest->processRequest();
```

In case the URL matches the CLASS NAME, everything works fine. But if I want to give my service an ALIAS, say, Tpl instead of TemplateProvider, the REST router will not be able to match it.

`http://api.com/TemplateProvider/` => GOOD! (corresponds to \Modules\Core\Common\Php\Services\TemplateProvider)

`http://api.com/SiteWideConstants/`=> GOOD! (corresponds to \Modules\Core\Common\Php\Services\SiteWideConstants)

But if I set my config like this:

``` yaml
RestServices:
    Tpl: \Modules\Core\Common\Php\Services\TemplateProvider
    Constants: \Modules\Core\Common\Php\Services\SiteWideConstants
```

`http://api.com/Tpl/` => MATCH FAILS! Different class name and URL
`http://api.com/Constants/` => MATCH FAILS! Different class name and URL

Would be nice to be able to give API routes standalone aliases, not related to class name.
