### ISSUE TITLE
Mongo - set default value for ResultClass

### ISSUE THREAD

**Issue by SvenAlHamad** [Webiny/Framework#24]
It would be good to set `\Webiny\Component\Mongo\MongoResult` as the default `ResultClass`, so that I don't need to define it in the configuration. The same rule should apply for the `Driver` also.

```yaml
Mongo:
    Services:
        Todo:
            Class: \Webiny\Component\Mongo\Mongo
            Arguments:
                Host: 127.0.0.1:27017
                Database: Foo
    Driver: \Webiny\Component\Mongo\Driver\Mongo 
    ResultClass: \Webiny\Component\Mongo\MongoResult
```
