### ISSUE TITLE
Ability to tag routes (Router)

### ISSUE THREAD

**Issue by adrian1358** [Webiny/Framework#45]
It would be nice to be able to enter tags for routes, so that we can take some additional actions in our app if needed.

Like this example:

```
    Router:
        Routes:
            BlogTag:
                Path: blog/tag/{tag}
                Callback: MyApp\Blog\showTag
            BlogComments:
                Path: blog/post/{id}/comments
                Callback:
                    Class: MyApp\Blog
                    Method: showComments
            CronJob:
                    Path: 'something/cron'
                    Tags: [system, cron]
                    Class: MyApp\Cron
                    Method: resetData
            LandingPage:
                    Path: 'application'
                    Tags: [system, angularApp]
                    Class: MyApp\App
                    Method: execute
```

Thank you ;)
